Repository Shimpyo-House/Shimpyo_BE, pull requests merged in 2023-12, with the labels that each got.

#89 refactor: 회원, Refresh 토큰 테이블 속성에 코멘트 추가
  README.md
  src/main/java/com/fc/shimpyo_be/domain/member/entity/Member.java
  src/main/java/com/fc/shimpyo_be/domain/member/entity/RefreshToken.java
Labels: 🚧refactoring

#91 refactor: 예약/예약 상품/장바구니/별점 테이블 column comment 추가
  src/main/java/com/fc/shimpyo_be/domain/cart/entity/Cart.java
  src/main/java/com/fc/shimpyo_be/domain/reservation/entity/Reservation.java
  src/main/java/com/fc/shimpyo_be/domain/reservationproduct/entity/ReservationProduct.java
  src/main/java/com/fc/shimpyo_be/domain/star/entity/Star.java
Labels: 🚧refactoring

#95 refactor: 숙소, 숙소 이미지, 객실 테이블에 comment를 추가합니다.
  src/main/java/com/fc/shimpyo_be/domain/product/entity/Product.java
  src/main/java/com/fc/shimpyo_be/domain/product/entity/ProductImage.java
  src/main/java/com/fc/shimpyo_be/domain/room/entity/Room.java
Labels: 🚧refactoring

#99 refactor: 예약 API Request Body 및 서비스 로직 리팩토링
  src/main/java/com/fc/shimpyo_be/domain/reservation/dto/CheckAvailableRoomsResultDto.java
  src/main/java/com/fc/shimpyo_be/domain/reservation/dto/request/PreoccupyRoomItemRequestDto.java
  src/main/java/com/fc/shimpyo_be/domain/reservation/dto/request/PreoccupyRoomsRequestDto.java
  src/main/java/com/fc/shimpyo_be/domain/reservation/dto/request/ReleaseRoomItemRequestDto.java
  src/main/java/com/fc/shimpyo_be/domain/reservation/dto/request/ReleaseRoomsRequestDto.java
  src/main/java/com/fc/shimpyo_be/domain/reservation/dto/request/SaveReservationRequestDto.java
  src/main/java/com/fc/shimpyo_be/domain/reservation/dto/response/ReservationInfoResponseDto.java
  src/main/java/com/fc/shimpyo_be/domain/reservation/dto/response/SaveReservationResponseDto.java
  src/main/java/com/fc/shimpyo_be/domain/reservation/dto/response/ValidationResultResponseDto.java
  src/main/java/com/fc/shimpyo_be/domain/reservation/service/ReservationService.java
  src/main/java/com/fc/shimpyo_be/domain/reservation/util/ReservationMapper.java
  src/main/java/com/fc/shimpyo_be/domain/reservationproduct/dto/request/ReservationProductRequestDto.java
  src/main/java/com/fc/shimpyo_be/domain/reservationproduct/dto/response/ReservationProductResponseDto.java
  src/main/java/com/fc/shimpyo_be/global/util/DateTimeUtil.java
  src/test/java/com/fc/shimpyo_be/config/TestDBCleanerConfig.java
  src/test/java/com/fc/shimpyo_be/domain/reservation/docs/ReservationRestControllerDocsTest.java
  src/test/java/com/fc/shimpyo_be/domain/reservation/unit/controller/ReservationRestControllerTest.java
  src/test/java/com/fc/shimpyo_be/domain/reservation/unit/facade/ReservationLockFacadeTest.java
  src/test/java/com/fc/shimpyo_be/domain/reservation/unit/service/GetReservationListServiceTest.java
  src/test/java/com/fc/shimpyo_be/domain/reservation/unit/service/ReservationServiceTest.java
Labels: 🚧refactoring, ✅Test

#96 refactor: 주문/결제페이지 객실 정보 조회 기능 개발
  src/main/java/com/fc/shimpyo_be/domain/reservationproduct/dto/request/ReservationProductRequestDto.java
  src/main/java/com/fc/shimpyo_be/domain/room/controller/RoomRestController.java
  src/main/java/com/fc/shimpyo_be/domain/room/dto/request/GetRoomListWithProductInfoRequestDto.java
  src/main/java/com/fc/shimpyo_be/domain/room/dto/response/RoomListWithProductInfoResponseDto.java
  src/main/java/com/fc/shimpyo_be/domain/room/dto/response/RoomWithProductResponseDto.java
  src/main/java/com/fc/shimpyo_be/domain/room/repository/RoomRepository.java
  src/main/java/com/fc/shimpyo_be/domain/room/repository/RoomRepositoryCustom.java
  src/main/java/com/fc/shimpyo_be/domain/room/repository/RoomRepositoryImpl.java
  src/main/java/com/fc/shimpyo_be/domain/room/service/RoomService.java
  src/main/java/com/fc/shimpyo_be/domain/room/util/RoomMapper.java
  src/test/java/com/fc/shimpyo_be/domain/room/docs/RoomRestControllerDocsTest.java
  src/test/java/com/fc/shimpyo_be/domain/room/unit/controller/RoomRestControllerTest.java
  src/test/java/com/fc/shimpyo_be/domain/room/unit/repository/RoomRepositoryTest.java
  src/test/java/com/fc/shimpyo_be/domain/room/unit/service/RoomServiceTest.java
Labels: 🛠️feature, 🚧refactoring, ✅Test

#107 #103 feature,test: 숙소 전체 조회에서 객실 최대 인원 및 pageCount 추가 응답
  .gitignore
  src/main/java/com/fc/shimpyo_be/domain/product/controller/ProductRestController.java
  src/main/java/com/fc/shimpyo_be/domain/product/dto/request/SearchKeywordRequest.java
  src/main/java/com/fc/shimpyo_be/domain/product/dto/response/PaginatedProductResponse.java
  src/main/java/com/fc/shimpyo_be/domain/product/dto/response/ProductAddressResponse.java
  src/main/java/com/fc/shimpyo_be/domain/product/dto/response/ProductDetailsResponse.java
  src/main/java/com/fc/shimpyo_be/domain/product/repository/ProductCustomRepository.java
  src/main/java/com/fc/shimpyo_be/domain/product/repository/ProductCustomRepositoryImpl.java
  src/main/java/com/fc/shimpyo_be/domain/product/repository/ProductRepository.java
  src/main/java/com/fc/shimpyo_be/domain/product/repository/model/ProductSpecification.java
  src/main/java/com/fc/shimpyo_be/domain/product/service/ProductService.java
  src/main/java/com/fc/shimpyo_be/domain/product/util/ProductMapper.java
  src/main/java/com/fc/shimpyo_be/domain/room/dto/response/RoomResponse.java
  src/main/java/com/fc/shimpyo_be/domain/room/util/RoomMapper.java
  src/main/resources/application.yaml
  src/test/java/com/fc/shimpyo_be/domain/product/docs/ProductRestIntegrationDocsTest.java
  src/test/java/com/fc/shimpyo_be/domain/product/unit/controller/ProductRestControllerTest.java
  src/test/java/com/fc/shimpyo_be/domain/product/unit/repository/ProductRepositoryTest.java
  src/test/java/com/fc/shimpyo_be/domain/product/unit/service/ProductServiceTest.java
Labels: 🛠️feature, ✅Test

#110 fix: 객실 조회에서 fetchJoin을 사용하면 너무 많은 데이터가 영속성 컨텍스트에 저장되, 서버 메모리가 버티질 못함.
  src/main/java/com/fc/shimpyo_be/domain/product/repository/ProductCustomRepositoryImpl.java
Labels: 🛠️feature, ✅Test

#112 feature, test: 상세 조회- 보유수량 및 roomCode, 장바구니 및 예약 API 수정
  src/main/java/com/fc/shimpyo_be/domain/cart/dto/request/CartCreateRequest.java
  src/main/java/com/fc/shimpyo_be/domain/cart/dto/response/CartDeleteResponse.java
  src/main/java/com/fc/shimpyo_be/domain/cart/dto/response/CartResponse.java
  src/main/java/com/fc/shimpyo_be/domain/cart/entity/Cart.java
  src/main/java/com/fc/shimpyo_be/domain/cart/repository/CartRepository.java
  src/main/java/com/fc/shimpyo_be/domain/cart/service/CartService.java
  src/main/java/com/fc/shimpyo_be/domain/cart/util/CartMapper.java
  src/main/java/com/fc/shimpyo_be/domain/product/repository/ProductCustomRepositoryImpl.java
  src/main/java/com/fc/shimpyo_be/domain/product/service/ProductService.java
  src/main/java/com/fc/shimpyo_be/domain/product/util/ProductMapper.java
  src/main/java/com/fc/shimpyo_be/domain/room/dto/response/RoomResponse.java
  src/main/java/com/fc/shimpyo_be/domain/room/repository/RoomRepository.java
  src/main/java/com/fc/shimpyo_be/domain/room/util/RoomMapper.java
  src/test/java/com/fc/shimpyo_be/domain/cart/docs/CartRestIntegrationDocsTest.java
  src/test/java/com/fc/shimpyo_be/domain/cart/factory/CartFactory.java
  src/test/java/com/fc/shimpyo_be/domain/cart/unit/controller/CartRestControllerTest.java
  src/test/java/com/fc/shimpyo_be/domain/cart/unit/service/CartRestServiceTest.java
  src/test/java/com/fc/shimpyo_be/domain/product/docs/ProductRestIntegrationDocsTest.java
  src/test/java/com/fc/shimpyo_be/domain/product/factory/ProductFactory.java
  src/test/java/com/fc/shimpyo_be/domain/product/unit/repository/ProductRepositoryTest.java
  src/test/java/com/fc/shimpyo_be/domain/product/unit/service/ProductServiceTest.java
Labels: 🛠️feature, ✅Test

#114 refactor: 객실 예약 가능 확인 및 선점 API 로직 수정
  src/main/java/com/fc/shimpyo_be/domain/reservation/controller/ReservationRestController.java
  src/main/java/com/fc/shimpyo_be/domain/reservation/dto/CheckAvailableRoomsResultDto.java
  src/main/java/com/fc/shimpyo_be/domain/reservation/dto/request/PreoccupyRoomItemRequestDto.java
  src/main/java/com/fc/shimpyo_be/domain/reservation/dto/response/ValidatePreoccupyResultResponseDto.java
  src/main/java/com/fc/shimpyo_be/domain/reservation/dto/response/ValidatePreoccupyRoomResponseDto.java
  src/main/java/com/fc/shimpyo_be/domain/reservation/dto/response/ValidateReservationResultResponseDto.java
  src/main/java/com/fc/shimpyo_be/domain/reservation/exception/PreoccupyNotAvailableException.java
  src/main/java/com/fc/shimpyo_be/domain/reservation/exception/ReservationRestControllerAdvice.java
  src/main/java/com/fc/shimpyo_be/domain/reservation/exception/ReserveNotAvailableException.java
  src/main/java/com/fc/shimpyo_be/domain/reservation/facade/PreoccupyRoomsLockFacade.java
  src/main/java/com/fc/shimpyo_be/domain/reservation/facade/ReservationLockFacade.java
  src/main/java/com/fc/shimpyo_be/domain/reservation/service/PreoccupyRoomsService.java
  src/main/java/com/fc/shimpyo_be/domain/reservation/service/ReservationService.java
  src/main/java/com/fc/shimpyo_be/domain/room/repository/RoomRepository.java
  src/main/java/com/fc/shimpyo_be/domain/room/service/RoomService.java
  src/test/java/com/fc/shimpyo_be/domain/reservation/docs/ReservationRestControllerDocsTest.java
  src/test/java/com/fc/shimpyo_be/domain/reservation/unit/controller/ReservationRestControllerTest.java
  src/test/java/com/fc/shimpyo_be/domain/reservation/unit/facade/PreoccupyRoomsLockFacadeTest.java
Labels: 🚧refactoring, ✅Test

#111 refactor: Open API 서비스 리팩토링
  src/main/java/com/fc/shimpyo_be/domain/product/exception/InvalidDataException.java
  src/main/java/com/fc/shimpyo_be/domain/product/service/OpenApiService.java
Labels: 🚧refactoring

#116 feat: 즐겨찾기 기능 구현
  src/docs/asciidoc/favorite/favorite-api.adoc
  src/main/java/com/fc/shimpyo_be/domain/favorite/controller/FavoriteRestController.java
  src/main/java/com/fc/shimpyo_be/domain/favorite/dto/FavoriteResponseDto.java
  src/main/java/com/fc/shimpyo_be/domain/favorite/dto/FavoritesResponseDto.java
  src/main/java/com/fc/shimpyo_be/domain/favorite/exception/FavoriteAlreadyRegisterException.java
  src/main/java/com/fc/shimpyo_be/domain/favorite/exception/FavoriteNotFoundException.java
  src/main/java/com/fc/shimpyo_be/domain/favorite/repository/FavoriteCustomRepository.java
  src/main/java/com/fc/shimpyo_be/domain/favorite/repository/FavoriteCustomRepositoryImpl.java
  src/main/java/com/fc/shimpyo_be/domain/favorite/repository/FavoriteRepository.java
  src/main/java/com/fc/shimpyo_be/domain/favorite/service/FavoriteService.java
  src/main/java/com/fc/shimpyo_be/global/exception/ErrorCode.java
  src/test/java/com/fc/shimpyo_be/domain/favorite/docs/FavoriteRestControllerDocsTest.java
  src/test/java/com/fc/shimpyo_be/domain/favorite/unit/controller/FavoriteRestControllerTest.java
  src/test/java/com/fc/shimpyo_be/domain/favorite/unit/repository/FavoriteRepositoryTest.java
  src/test/java/com/fc/shimpyo_be/domain/favorite/unit/service/FavoriteServiceTest.java
Labels: 📚document, 🛠️feature, ✅Test

#119 hotfix: 주문 페이지를 위한 숙소/객실 정보 리스트 조회 에러 수정
  src/main/java/com/fc/shimpyo_be/domain/room/controller/RoomRestController.java
  src/main/java/com/fc/shimpyo_be/domain/room/dto/request/GetRoomListWithProductInfoRequestDto.java
  src/test/java/com/fc/shimpyo_be/domain/room/docs/RoomRestControllerDocsTest.java
  src/test/java/com/fc/shimpyo_be/domain/room/unit/controller/RoomRestControllerTest.java
Labels: 🐞bug, 🚧refactoring, ✅Test

#117 feat: 별점 등록 기한 제한 검증 로직 구현
  src/main/java/com/fc/shimpyo_be/domain/star/controller/StarRestController.java
  src/main/java/com/fc/shimpyo_be/domain/star/exception/ExpiredRegisterDateException.java
  src/main/java/com/fc/shimpyo_be/domain/star/service/StarService.java
  src/main/java/com/fc/shimpyo_be/global/exception/ErrorCode.java
  src/test/java/com/fc/shimpyo_be/domain/star/unit/controller/StarRestControllerTest.java
  src/test/java/com/fc/shimpyo_be/domain/star/unit/service/StarServiceTest.java
Labels: 🚧refactoring, ✅Test

#124 feature, test: 전체 조회 및 상세 조회시, 즐겨찾기 여부 추가 응답!!
  src/main/java/com/fc/shimpyo_be/domain/favorite/service/FavoriteService.java
  src/main/java/com/fc/shimpyo_be/domain/product/entity/Product.java
  src/main/java/com/fc/shimpyo_be/domain/product/service/ProductService.java
  src/main/java/com/fc/shimpyo_be/domain/product/util/ProductMapper.java
  src/main/java/com/fc/shimpyo_be/global/util/SecurityUtil.java
  src/test/java/com/fc/shimpyo_be/domain/product/docs/ProductRestIntegrationDocsTest.java
  src/test/java/com/fc/shimpyo_be/domain/product/unit/controller/ProductRestControllerTest.java
  src/test/java/com/fc/shimpyo_be/domain/product/unit/service/ProductServiceTest.java
Labels: 🛠️feature, ✅Test

#120 refactor: 즐겨찾기 응답 시 isLast 필드 제외
  src/main/java/com/fc/shimpyo_be/domain/favorite/dto/FavoritesResponseDto.java
  src/main/java/com/fc/shimpyo_be/domain/favorite/service/FavoriteService.java
  src/test/java/com/fc/shimpyo_be/domain/favorite/docs/FavoriteRestControllerDocsTest.java
  src/test/java/com/fc/shimpyo_be/domain/favorite/unit/controller/FavoriteRestControllerTest.java
  src/test/java/com/fc/shimpyo_be/domain/favorite/unit/repository/FavoriteRepositoryTest.java
Labels: 🚧refactoring, ✅Test

#126 hotfix: 필터를 거치지 않는 url에 authentication이 초기화 안되있을 걸 예상햇지만 초기화 되있는 이슈
  src/main/java/com/fc/shimpyo_be/global/util/SecurityUtil.java
Labels: 🐞bug, 🧑🏻‍🔧fix

#128 fix: 장바구니 추가 시, 날짜 검증 수정 및 querydsl 사용
  src/main/java/com/fc/shimpyo_be/domain/cart/repository/CartCustomRepository.java
  src/main/java/com/fc/shimpyo_be/domain/cart/repository/CartCustomRepositoryImpl.java
  src/main/java/com/fc/shimpyo_be/domain/cart/repository/CartRepository.java
  src/main/java/com/fc/shimpyo_be/domain/cart/service/CartService.java
  src/test/java/com/fc/shimpyo_be/domain/cart/docs/CartRestIntegrationDocsTest.java
  src/test/java/com/fc/shimpyo_be/domain/cart/unit/service/CartRestServiceTest.java
Labels: 🛠️feature, 🧑🏻‍🔧fix

#129 fix: 장바구니 조회 api 수정
  src/main/java/com/fc/shimpyo_be/domain/cart/service/CartService.java
  src/test/java/com/fc/shimpyo_be/domain/cart/unit/service/CartRestServiceTest.java
  src/test/java/com/fc/shimpyo_be/domain/star/unit/service/StarServiceTest.java
Labels: 🧑🏻‍🔧fix

#130 refactor, feat: 예약 선점/예약 저장 때 선점한 레디스키 만료기한 다르게 설정하도록 수정 & 예약 저장시 장바구니 삭제 로직 추가
  src/main/java/com/fc/shimpyo_be/domain/cart/service/CartService.java
  src/main/java/com/fc/shimpyo_be/domain/reservation/dto/ValidateReservationResultDto.java
  src/main/java/com/fc/shimpyo_be/domain/reservation/dto/request/PreoccupyRoomItemRequestDto.java
  src/main/java/com/fc/shimpyo_be/domain/reservation/dto/response/ValidatePreoccupyRoomResponseDto.java
  src/main/java/com/fc/shimpyo_be/domain/reservation/exception/ReserveNotAvailableException.java
  src/main/java/com/fc/shimpyo_be/domain/reservation/facade/ReservationLockFacade.java
  src/main/java/com/fc/shimpyo_be/domain/reservation/service/PreoccupyRoomsService.java
  src/main/java/com/fc/shimpyo_be/domain/reservation/service/ReservationService.java
  src/main/java/com/fc/shimpyo_be/domain/reservation/util/ReservationMapper.java
  src/main/java/com/fc/shimpyo_be/domain/reservationproduct/dto/request/ReservationProductRequestDto.java
  src/main/java/com/fc/shimpyo_be/global/exception/ErrorCode.java
  src/test/java/com/fc/shimpyo_be/domain/reservation/docs/ReservationRestControllerDocsTest.java
  src/test/java/com/fc/shimpyo_be/domain/reservation/unit/controller/ReservationRestControllerTest.java
  src/test/java/com/fc/shimpyo_be/domain/reservation/unit/facade/ReservationLockFacadeTest.java
  src/test/java/com/fc/shimpyo_be/domain/reservation/unit/service/ReservationServiceTest.java
  src/test/java/com/fc/shimpyo_be/domain/star/unit/service/StarServiceTest.java
Labels: 🛠️feature, 🚧refactoring, ✅Test

#131 refactor: Open API 활용서비스 리팩토링
  src/main/java/com/fc/shimpyo_be/domain/product/service/OpenApiService.java
Labels: 🚧refactoring

#132 refactor: 회원 도메인 리팩토링
  src/main/java/com/fc/shimpyo_be/domain/member/controller/AuthRestController.java
  src/main/java/com/fc/shimpyo_be/domain/member/controller/MemberRestController.java
  src/main/java/com/fc/shimpyo_be/domain/member/dto/request/CheckPasswordRequestDto.java
  src/main/java/com/fc/shimpyo_be/domain/member/dto/request/RefreshRequestDto.java
  src/main/java/com/fc/shimpyo_be/domain/member/dto/request/SignInRequestDto.java
  src/main/java/com/fc/shimpyo_be/domain/member/dto/request/SignUpRequestDto.java
  src/main/java/com/fc/shimpyo_be/domain/member/dto/request/UpdateMemberRequestDto.java
  src/main/java/com/fc/shimpyo_be/domain/member/dto/response/MemberResponseDto.java
  src/main/java/com/fc/shimpyo_be/domain/member/dto/response/SignInResponseDto.java
  src/main/java/com/fc/shimpyo_be/domain/member/dto/response/TokenResponseDto.java
  src/main/java/com/fc/shimpyo_be/domain/member/entity/Member.java
  src/main/java/com/fc/shimpyo_be/domain/member/entity/RefreshToken.java
  src/test/java/com/fc/shimpyo_be/domain/member/docs/AuthRestControllerDocsTest.java
Labels: 🚧refactoring

#133 refactor: 즐겨찾기 도메인 리팩토링
  src/main/java/com/fc/shimpyo_be/domain/favorite/controller/FavoriteRestController.java
  src/main/java/com/fc/shimpyo_be/domain/favorite/dto/FavoriteResponseDto.java
  src/main/java/com/fc/shimpyo_be/domain/favorite/dto/FavoritesResponseDto.java
  src/main/java/com/fc/shimpyo_be/domain/favorite/entity/Favorite.java
  src/test/java/com/fc/shimpyo_be/domain/favorite/docs/FavoriteRestControllerDocsTest.java
  src/test/java/com/fc/shimpyo_be/domain/favorite/unit/controller/FavoriteRestControllerTest.java
Labels: 🚧refactoring

#134 refactor: 예약 도메인 리팩토링
  src/main/java/com/fc/shimpyo_be/domain/reservation/constant/ReservationValidationConstants.java
  src/main/java/com/fc/shimpyo_be/domain/reservation/controller/ReservationRestController.java
  src/main/java/com/fc/shimpyo_be/domain/reservation/dto/request/PreoccupyRoomItemRequestDto.java
  src/main/java/com/fc/shimpyo_be/domain/reservation/dto/request/PreoccupyRoomsRequestDto.java
  src/main/java/com/fc/shimpyo_be/domain/reservation/dto/request/ReleaseRoomItemRequestDto.java
  src/main/java/com/fc/shimpyo_be/domain/reservation/dto/request/ReleaseRoomsRequestDto.java
  src/main/java/com/fc/shimpyo_be/domain/reservation/dto/request/SaveReservationRequestDto.java
  src/main/java/com/fc/shimpyo_be/domain/reservation/entity/Reservation.java
  src/main/java/com/fc/shimpyo_be/domain/reservation/exception/InvalidRequestException.java
  src/main/java/com/fc/shimpyo_be/domain/reservation/facade/PreoccupyRoomsLockFacade.java
  src/main/java/com/fc/shimpyo_be/domain/reservation/facade/ReservationLockFacade.java
  src/main/java/com/fc/shimpyo_be/domain/reservation/service/PreoccupyRoomsService.java
  src/main/java/com/fc/shimpyo_be/domain/reservation/service/ReservationService.java
  src/main/java/com/fc/shimpyo_be/domain/reservation/util/mapper/ReservationMapper.java
  src/main/java/com/fc/shimpyo_be/domain/reservationproduct/dto/request/ReservationProductRequestDto.java
  src/main/java/com/fc/shimpyo_be/domain/room/exception/RoomNotFoundException.java
  src/main/java/com/fc/shimpyo_be/domain/room/service/RoomService.java
  src/test/java/com/fc/shimpyo_be/domain/reservation/unit/service/GetReservationListServiceTest.java
  src/test/java/com/fc/shimpyo_be/domain/reservation/unit/service/ReservationServiceTest.java
Labels: 🚧refactoring, ✅Test

#135 refactor: 예약 상품/객실 도메인 리팩토링
  src/main/java/com/fc/shimpyo_be/domain/reservationproduct/constant/ReservationProductValidationConstants.java
  src/main/java/com/fc/shimpyo_be/domain/reservationproduct/controller/ReservationProductRestController.java
  src/main/java/com/fc/shimpyo_be/domain/reservationproduct/dto/request/ReservationProductRequestDto.java
  src/main/java/com/fc/shimpyo_be/domain/reservationproduct/entity/ReservationProduct.java
  src/main/java/com/fc/shimpyo_be/domain/reservationproduct/service/ReservationProductService.java
  src/main/java/com/fc/shimpyo_be/domain/room/constant/RoomValidationConstants.java
  src/main/java/com/fc/shimpyo_be/domain/room/controller/RoomRestController.java
  src/main/java/com/fc/shimpyo_be/domain/room/entity/Room.java
  src/main/java/com/fc/shimpyo_be/domain/room/entity/RoomImage.java
  src/main/java/com/fc/shimpyo_be/domain/room/entity/RoomOption.java
  src/main/java/com/fc/shimpyo_be/domain/room/entity/RoomPrice.java
  src/main/java/com/fc/shimpyo_be/domain/room/service/RoomService.java
Labels: 🚧refactoring, ✅Test

#136 refactor: 별점 도메인 리팩토링
  src/main/java/com/fc/shimpyo_be/domain/star/constant/StarValidationConstants.java
  src/main/java/com/fc/shimpyo_be/domain/star/controller/StarRestController.java
  src/main/java/com/fc/shimpyo_be/domain/star/dto/request/StarRegisterRequestDto.java
  src/main/java/com/fc/shimpyo_be/domain/star/entity/Star.java
  src/main/java/com/fc/shimpyo_be/domain/star/service/StarService.java
  src/test/java/com/fc/shimpyo_be/domain/star/docs/StarRestControllerDocsTest.java
Labels: 🚧refactoring, ✅Test

#137 refactor: adoc 리팩토링
  src/docs/asciidoc/cart/cart-api.adoc
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/product/product-api.adoc
  src/docs/asciidoc/room/room-api.adoc
Labels: 📚document

#139 refactor: product - room - cart 내 log.debug 삭제 및 접근 제어자 수정, transaction(readOnly=true)를 통해 성능 향상
  src/main/java/com/fc/shimpyo_be/domain/cart/controller/CartRestController.java
  src/main/java/com/fc/shimpyo_be/domain/cart/dto/response/CartResponse.java
  src/main/java/com/fc/shimpyo_be/domain/product/controller/ProductRestController.java
  src/main/java/com/fc/shimpyo_be/domain/room/dto/response/RoomResponse.java
Labels: 🚧refactoring

#140 docs: 2차 스프린트 개발을 적용한 리드미 수정
  README.md
  src/main/resources/image/cart-docs.png
  src/main/resources/image/docs-error.png
  src/main/resources/image/docs/cart-docs.png
  src/main/resources/image/docs/favorite-docs.png
  src/main/resources/image/docs/index-docs.png
  src/main/resources/image/docs/member-docs.png
  src/main/resources/image/docs/product-docs.png
  src/main/resources/image/docs/reservation-docs.png
  src/main/resources/image/docs/reservation-product-docs.png
  src/main/resources/image/docs/room-docs.png
  src/main/resources/image/docs/star-docs.png
  src/main/resources/image/erd.png
  src/main/resources/image/main-page.png
  src/main/resources/image/member-docs.png
  src/main/resources/image/product-docs.png
  src/main/resources/image/reservation-docs.png
  src/main/resources/image/reservation-product-docs.png
  src/main/resources/image/star-docs.png
  src/main/resources/image/wrapper-error-1.png
  src/main/resources/image/wrapper-error-2.png
Labels: 📚document

#142 docs: 리드미 수정
  README.md
Labels: 📚document

#143 docs: 리드미에 리팩토링 이후 추가된 기능 목차 추가
  README.md
Labels: 📚document
