Repository Shimpyo-House/Shimpyo_BE, pull requests merged in 2023-11, with the labels that each got.

#2 feat: 개발 환경 구축
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/gradle.yml
  .gitignore
  build.gradle
  src/main/java/com/fc/shimpyo_be/ShimpyoBeApplication.java
  src/main/java/com/fc/shimpyo_be/domain/favorite/entity/Favorite.java
  src/main/java/com/fc/shimpyo_be/domain/favorite/repository/FavoriteRepository.java
  src/main/java/com/fc/shimpyo_be/domain/member/entity/Member.java
  src/main/java/com/fc/shimpyo_be/domain/member/repository/MemberRepository.java
  src/main/java/com/fc/shimpyo_be/domain/order/entity/Order.java
  src/main/java/com/fc/shimpyo_be/domain/order/entity/PayMethod.java
  src/main/java/com/fc/shimpyo_be/domain/order/repository/OrderRepository.java
  src/main/java/com/fc/shimpyo_be/domain/orderproduct/entity/OrderProduct.java
  src/main/java/com/fc/shimpyo_be/domain/orderproduct/repository/OrderProductRepository.java
  src/main/java/com/fc/shimpyo_be/domain/product/entity/Category.java
  src/main/java/com/fc/shimpyo_be/domain/product/entity/Product.java
  src/main/java/com/fc/shimpyo_be/domain/product/repository/ProductRepository.java
  src/main/java/com/fc/shimpyo_be/domain/room/entity/Room.java
  src/main/java/com/fc/shimpyo_be/domain/room/repository/RoomRepository.java
  src/main/java/com/fc/shimpyo_be/domain/star/entity/Star.java
  src/main/java/com/fc/shimpyo_be/domain/star/repository/StarRepository.java
  src/main/java/com/fc/shimpyo_be/global/common/BaseTimeEntity.java
  src/main/java/com/fc/shimpyo_be/global/common/ResponseDto.java
  src/main/java/com/fc/shimpyo_be/global/config/JpaAuditConfiguration.java
  src/main/java/com/fc/shimpyo_be/global/exception/GlobalControllerAdvice.java
  src/main/java/com/fc/shimpyo_be/global/util/QueryDslUtil.java
  src/main/resources/application.yaml
  src/test/java/com/fc/shimpyo_be/config/RestDocsConfig.java
  src/test/java/com/fc/shimpyo_be/config/RestDocsSupport.java
  src/test/java/com/fc/shimpyo_be/config/TestJpaConfig.java
  src/test/resources/application.yaml
  src/test/resources/org/springframework/restdocs/templates/path-parameters.snippet
  src/test/resources/org/springframework/restdocs/templates/query-parameters.snippet
  src/test/resources/org/springframework/restdocs/templates/request-fields.snippet
  src/test/resources/org/springframework/restdocs/templates/response-fields.snippet
Labels: 📚document, 🛠️feature, ⚙Setting, ✅Test

#7 feat: 회원 가입, 로그인, 토큰 재발급 기능 구현
  src/main/java/com/fc/shimpyo_be/domain/member/controller/AuthRestController.java
  src/main/java/com/fc/shimpyo_be/domain/member/controller/AuthRestControllerAdvice.java
  src/main/java/com/fc/shimpyo_be/domain/member/dto/request/RefreshRequestDto.java
  src/main/java/com/fc/shimpyo_be/domain/member/dto/request/SignInRequestDto.java
  src/main/java/com/fc/shimpyo_be/domain/member/dto/request/SignUpRequestDto.java
  src/main/java/com/fc/shimpyo_be/domain/member/dto/response/MemberResponseDto.java
  src/main/java/com/fc/shimpyo_be/domain/member/dto/response/SignInResponseDto.java
  src/main/java/com/fc/shimpyo_be/domain/member/dto/response/TokenResponseDto.java
  src/main/java/com/fc/shimpyo_be/domain/member/entity/Authority.java
  src/main/java/com/fc/shimpyo_be/domain/member/entity/Member.java
  src/main/java/com/fc/shimpyo_be/domain/member/entity/RefreshToken.java
  src/main/java/com/fc/shimpyo_be/domain/member/exception/AlreadyExistsMemberException.java
  src/main/java/com/fc/shimpyo_be/domain/member/exception/InvalidRefreshTokenException.java
  src/main/java/com/fc/shimpyo_be/domain/member/exception/LoggedOutException.java
  src/main/java/com/fc/shimpyo_be/domain/member/exception/MemberNotFoundException.java
  src/main/java/com/fc/shimpyo_be/domain/member/exception/UnmatchedMemberException.java
  src/main/java/com/fc/shimpyo_be/domain/member/exception/UnmatchedPasswordException.java
  src/main/java/com/fc/shimpyo_be/domain/member/repository/MemberRepository.java
  src/main/java/com/fc/shimpyo_be/domain/member/repository/RefreshTokenRepository.java
  src/main/java/com/fc/shimpyo_be/domain/member/service/AuthService.java
  src/main/java/com/fc/shimpyo_be/domain/member/service/MemberService.java
  src/main/java/com/fc/shimpyo_be/global/config/CorsConfig.java
  src/main/java/com/fc/shimpyo_be/global/config/CustomUserDetailsService.java
  src/main/java/com/fc/shimpyo_be/global/config/SecurityConfig.java
  src/main/java/com/fc/shimpyo_be/global/config/jwt/JwtAccessDeniedHandler.java
  src/main/java/com/fc/shimpyo_be/global/config/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/com/fc/shimpyo_be/global/config/jwt/JwtAuthenticationFilter.java
  src/main/java/com/fc/shimpyo_be/global/config/jwt/JwtSecurityConfig.java
  src/main/java/com/fc/shimpyo_be/global/config/jwt/JwtTokenProvider.java
  src/main/java/com/fc/shimpyo_be/global/exception/GlobalControllerAdvice.java
  src/main/java/com/fc/shimpyo_be/global/util/SecurityUtil.java
  src/main/resources/application.yaml
  src/test/java/com/fc/shimpyo_be/domain/member/docs/AuthRestControllerDocsTest.java
  src/test/java/com/fc/shimpyo_be/domain/member/unit/controller/AuthRestControllerTest.java
  src/test/java/com/fc/shimpyo_be/domain/member/unit/repository/MemberRepositoryTest.java
  src/test/java/com/fc/shimpyo_be/domain/member/unit/repository/RefreshTokenRepositoryTest.java
  src/test/java/com/fc/shimpyo_be/domain/member/unit/service/AuthServiceTest.java
  src/test/resources/application.yaml
Labels: 🛠️feature, ✅Test

#14 fix: 비밀번호 확인 API 문서화를 위해 adoc 파일에 추가
  src/docs/asciidoc/member/member-api.adoc
  src/test/java/com/fc/shimpyo_be/domain/member/docs/MemberRestControllerDocsTest.java
Labels: 📚document, 🧑🏻‍🔧fix, ✅Test

#19 fix: workflow file, dockerfile:이미 진행된 빌드 과정 생략
  .github/workflows/shimpyoDeploy.yml
  Dockerfile
Labels: 🧑🏻‍🔧fix

#20 fix: build action 사용 (cd workflow 파일 내)
  .github/workflows/shimpyoDeploy.yml
Labels: 🧑🏻‍🔧fix

#22 refactor: 도커 및 CD 재설정
  .github/workflows/shimpyoDeploy.yml
  .gitignore
  docker-compose.yml
  mariadb/config/my.cnf
  redis/config/redis.cnf
  src/main/resources/application.yaml
Labels: 🛠️feature, ⚙Setting

#23 fix: 오타 수정
  .github/workflows/shimpyoDeploy.yml
Labels: 🧑🏻‍🔧fix

#24 fix: action CD base64 디코딩 에러 수정
  .github/workflows/shimpyoDeploy.yml
Labels: 🧑🏻‍🔧fix

#8 feat: 상품 전체 조회 및 상세 조회 기능 구현
  src/main/java/com/fc/shimpyo_be/domain/product/controller/ProductRestController.java
  src/main/java/com/fc/shimpyo_be/domain/product/dto/request/SearchKeywordRequest.java
  src/main/java/com/fc/shimpyo_be/domain/product/dto/response/ProductDetailsResponse.java
  src/main/java/com/fc/shimpyo_be/domain/product/dto/response/ProductResponse.java
  src/main/java/com/fc/shimpyo_be/domain/product/entity/Category.java
  src/main/java/com/fc/shimpyo_be/domain/product/entity/Product.java
  src/main/java/com/fc/shimpyo_be/domain/product/exception/ProductNotFoundException.java
  src/main/java/com/fc/shimpyo_be/domain/product/exception/RoomNotFoundException.java
  src/main/java/com/fc/shimpyo_be/domain/product/exception/RoomNotReserveException.java
  src/main/java/com/fc/shimpyo_be/domain/product/repository/ProductRepository.java
  src/main/java/com/fc/shimpyo_be/domain/product/repository/model/ProductSpecification.java
  src/main/java/com/fc/shimpyo_be/domain/product/service/ProductService.java
  src/main/java/com/fc/shimpyo_be/domain/product/util/CategoryConverter.java
  src/main/java/com/fc/shimpyo_be/domain/product/util/ImageUrlParser.java
  src/main/java/com/fc/shimpyo_be/domain/product/util/PageableValidator.java
  src/main/java/com/fc/shimpyo_be/domain/product/util/ProductMapper.java
  src/main/java/com/fc/shimpyo_be/domain/product/util/model/PageableConstraint.java
  src/main/java/com/fc/shimpyo_be/domain/room/dto/response/RoomResponse.java
  src/main/java/com/fc/shimpyo_be/domain/room/entity/Room.java
  src/main/java/com/fc/shimpyo_be/domain/room/util/RoomMapper.java
  src/main/java/com/fc/shimpyo_be/global/exception/ApplicationException.java
  src/main/java/com/fc/shimpyo_be/global/exception/ErrorCode.java
  src/main/java/com/fc/shimpyo_be/global/exception/GlobalControllerAdvice.java
  src/main/java/com/fc/shimpyo_be/global/util/DateTimeUtil.java
  src/test/java/com/fc/shimpyo_be/domain/product/controller/ProductIntegrationTest.java
  src/test/java/com/fc/shimpyo_be/domain/product/factory/ProductFactory.java
  src/test/java/com/fc/shimpyo_be/domain/product/model/Area.java
Labels: 🛠️feature, 🚧refactoring, ✅Test

#32 회원 정보 조회 기능 구현
  src/docs/asciidoc/member/member-api.adoc
  src/main/java/com/fc/shimpyo_be/domain/member/controller/MemberRestController.java
  src/main/java/com/fc/shimpyo_be/domain/member/dto/response/CheckPasswordResponseDto.java
  src/main/java/com/fc/shimpyo_be/domain/member/service/AuthService.java
  src/main/java/com/fc/shimpyo_be/domain/member/service/MemberService.java
  src/test/java/com/fc/shimpyo_be/domain/member/docs/MemberRestControllerDocsTest.java
  src/test/java/com/fc/shimpyo_be/domain/member/unit/controller/MemberRestControllerTest.java
  src/test/java/com/fc/shimpyo_be/domain/member/unit/service/AuthServiceTest.java
  src/test/java/com/fc/shimpyo_be/domain/member/unit/service/MemberServiceTest.java
Labels: 📚document, 🛠️feature, 🧑🏻‍🔧fix, ✅Test

#28 refacotr: PR 템플릿 파일 이름 변경
  .github/pull_request_template.md
Labels: 📚document

#36 CORS allow origin 버그 해결
  src/main/java/com/fc/shimpyo_be/global/config/CorsConfig.java
Labels: 🧑🏻‍🔧fix, ⚙Setting

#34 상품 이미지 테이블을 추가하다!
  src/main/java/com/fc/shimpyo_be/domain/product/controller/ProductRestController.java
  src/main/java/com/fc/shimpyo_be/domain/product/entity/Product.java
  src/main/java/com/fc/shimpyo_be/domain/product/entity/ProductImage.java
  src/main/java/com/fc/shimpyo_be/domain/product/repository/ProductImageRepository.java
  src/main/java/com/fc/shimpyo_be/domain/product/repository/ProductRepository.java
  src/main/java/com/fc/shimpyo_be/domain/product/service/ProductService.java
  src/main/java/com/fc/shimpyo_be/domain/product/util/ProductMapper.java
  src/main/java/com/fc/shimpyo_be/global/util/DateTimeUtil.java
  src/main/java/com/fc/shimpyo_be/global/util/DateUtil.java
  src/test/java/com/fc/shimpyo_be/domain/product/controller/ProductIntegrationTest.java
  src/test/java/com/fc/shimpyo_be/domain/product/factory/ProductFactory.java
  src/test/java/com/fc/shimpyo_be/domain/product/model/RandomProductInfo.java
Labels: 🛠️feature, 🧑🏻‍🔧fix, 🚧refactoring, ✅Test

#38 fix: Member Docs 수정
  build.gradle
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/member/member-api.adoc
  src/test/java/com/fc/shimpyo_be/domain/member/docs/MemberRestControllerDocsTest.java
Labels: 📚document, 🧑🏻‍🔧fix

#45 feat: 장바구니 관련 기능을 구현했습니다.
  src/main/java/com/fc/shimpyo_be/domain/cart/controller/CartRestController.java
  src/main/java/com/fc/shimpyo_be/domain/cart/dto/request/CartCreateRequest.java
  src/main/java/com/fc/shimpyo_be/domain/cart/dto/response/CartDeleteResponse.java
  src/main/java/com/fc/shimpyo_be/domain/cart/dto/response/CartResponse.java
  src/main/java/com/fc/shimpyo_be/domain/cart/entity/Cart.java
  src/main/java/com/fc/shimpyo_be/domain/cart/exception/CartNotDeleteException.java
  src/main/java/com/fc/shimpyo_be/domain/cart/exception/CartNotFoundException.java
  src/main/java/com/fc/shimpyo_be/domain/cart/repository/CartRepository.java
  src/main/java/com/fc/shimpyo_be/domain/cart/service/CartService.java
  src/main/java/com/fc/shimpyo_be/domain/cart/util/CartMapper.java
  src/main/java/com/fc/shimpyo_be/domain/product/service/ProductService.java
  src/main/java/com/fc/shimpyo_be/global/exception/ErrorCode.java
  src/test/java/com/fc/shimpyo_be/domain/cart/docs/CartRestIntegrationDocsTest.java
  src/test/java/com/fc/shimpyo_be/domain/cart/factory/CartFactory.java
  src/test/java/com/fc/shimpyo_be/domain/cart/unit/controller/CartRestControllerTest.java
  src/test/java/com/fc/shimpyo_be/domain/cart/unit/service/CartRestServiceTest.java
  src/test/java/com/fc/shimpyo_be/domain/product/docs/ProductIntegrationDocsTest.java
Labels: 🛠️feature, ✅Test

#41 feat: 주문 목록 조회 기능 개발
  src/main/java/com/fc/shimpyo_be/domain/reservation/controller/ReservationRestController.java
  src/main/java/com/fc/shimpyo_be/domain/reservation/dto/response/ReservationInfoResponseDto.java
  src/main/java/com/fc/shimpyo_be/domain/reservation/entity/Reservation.java
  src/main/java/com/fc/shimpyo_be/domain/reservation/repository/ReservationRepository.java
  src/main/java/com/fc/shimpyo_be/domain/reservation/service/ReservationService.java
  src/main/java/com/fc/shimpyo_be/domain/reservationproduct/entity/ReservationProduct.java
  src/main/java/com/fc/shimpyo_be/domain/reservationproduct/repository/ReservationProductRepository.java
  src/main/java/com/fc/shimpyo_be/domain/reservationproduct/repository/ReservationProductRepositoryCustom.java
  src/main/java/com/fc/shimpyo_be/domain/reservationproduct/repository/ReservationProductRepositoryImpl.java
  src/main/java/com/fc/shimpyo_be/global/config/QuerydslConfig.java
  src/test/java/com/fc/shimpyo_be/config/TestQuerydslConfig.java
  src/test/java/com/fc/shimpyo_be/domain/cart/unit/controller/CartRestControllerTest.java
  src/test/java/com/fc/shimpyo_be/domain/member/unit/repository/MemberRepositoryTest.java
  src/test/java/com/fc/shimpyo_be/domain/member/unit/repository/RefreshTokenRepositoryTest.java
  src/test/java/com/fc/shimpyo_be/domain/reservation/docs/ReservationRestControllerDocsTest.java
  src/test/java/com/fc/shimpyo_be/domain/reservation/unit/controller/ReservationRestControllerTest.java
  src/test/java/com/fc/shimpyo_be/domain/reservation/unit/repository/ReservationRepositoryTest.java
  src/test/java/com/fc/shimpyo_be/domain/reservation/unit/service/GetReservationListServiceTest.java
  src/test/resources/application.yaml
  src/test/resources/testdata/reservation-repository-setup.sql
  src/test/resources/testdata/reservation-service-insert.sql
  src/test/resources/testdata/reservation-service-setup.sql
Labels: 🛠️feature, 🚧refactoring, ⚙Setting, ✅Test

#54 feat: Open API 활용 기능 구현
  .github/workflows/gradle.yml
  build.gradle
  src/main/java/com/fc/shimpyo_be/domain/product/controller/OpenApiRestController.java
  src/main/java/com/fc/shimpyo_be/domain/product/entity/Category.java
  src/main/java/com/fc/shimpyo_be/domain/product/entity/Product.java
  src/main/java/com/fc/shimpyo_be/domain/product/exception/OpenApiException.java
  src/main/java/com/fc/shimpyo_be/domain/product/service/OpenApiService.java
  src/main/java/com/fc/shimpyo_be/domain/product/util/CategoryConverter.java
  src/main/java/com/fc/shimpyo_be/global/config/SecurityConfig.java
  src/main/java/com/fc/shimpyo_be/global/exception/ErrorCode.java
  src/test/java/com/fc/shimpyo_be/domain/star/unit/service/StarServiceTest.java
Labels: 🛠️feature, ⚙Setting

#56 feat:날짜에 대한 유효성 검증을 하는 API를 추가했습니다.
  src/main/java/com/fc/shimpyo_be/domain/cart/controller/CartRestController.java
  src/main/java/com/fc/shimpyo_be/domain/product/controller/ProductRestController.java
  src/main/java/com/fc/shimpyo_be/domain/product/exception/InvalidDateException.java
  src/main/java/com/fc/shimpyo_be/global/exception/ErrorCode.java
  src/main/java/com/fc/shimpyo_be/global/util/DateTimeUtil.java
  src/test/java/com/fc/shimpyo_be/domain/cart/docs/CartRestIntegrationDocsTest.java
  src/test/java/com/fc/shimpyo_be/domain/cart/factory/CartFactory.java
  src/test/java/com/fc/shimpyo_be/domain/product/docs/ProductIntegrationDocsTest.java
Labels: 🛠️feature, ✅Test

#51 docs: 상품과 장바구니 관련 docs파일을 적용했습니다.
  src/docs/asciidoc/cart/cart-api.adoc
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/member/member-api.adoc
  src/docs/asciidoc/product/product-api.adoc
  src/main/java/com/fc/shimpyo_be/domain/product/controller/ProductRestController.java
  src/test/java/com/fc/shimpyo_be/domain/product/docs/ProductRestIntegrationDocsTest.java
  src/test/java/com/fc/shimpyo_be/domain/product/factory/ProductFactory.java
  src/test/java/com/fc/shimpyo_be/domain/product/unit/controller/ProductRestControllerTest.java
  src/test/java/com/fc/shimpyo_be/domain/product/unit/service/ProductServiceTest.java
Labels: 📚document, ✅Test

#67 feat: 인증/인가 컨트롤러에 로깅 추가 구현
  src/main/java/com/fc/shimpyo_be/domain/member/controller/AuthRestController.java
Labels: 🛠️feature

#57 feat: 주문 취소 기능 개발
  src/main/java/com/fc/shimpyo_be/domain/reservation/controller/ReservationRestController.java
  src/main/java/com/fc/shimpyo_be/domain/reservation/dto/request/ReleaseRoomItemRequestDto.java
  src/main/java/com/fc/shimpyo_be/domain/reservation/dto/request/ReleaseRoomsRequestDto.java
  src/main/java/com/fc/shimpyo_be/domain/reservation/entity/Reservation.java
  src/main/java/com/fc/shimpyo_be/domain/reservation/service/ReservationService.java
  src/main/java/com/fc/shimpyo_be/domain/reservationproduct/controller/ReservationProductRestController.java
  src/main/java/com/fc/shimpyo_be/domain/reservationproduct/entity/ReservationProduct.java
  src/main/java/com/fc/shimpyo_be/domain/reservationproduct/exception/ForbiddenCancelReservationProductException.java
  src/main/java/com/fc/shimpyo_be/domain/reservationproduct/exception/ReservationProductNotFoundException.java
  src/main/java/com/fc/shimpyo_be/domain/reservationproduct/repository/ReservationProductRepository.java
  src/main/java/com/fc/shimpyo_be/domain/reservationproduct/service/ReservationProductService.java
  src/main/java/com/fc/shimpyo_be/global/exception/ErrorCode.java
  src/test/java/com/fc/shimpyo_be/domain/reservation/docs/ReservationRestControllerDocsTest.java
  src/test/java/com/fc/shimpyo_be/domain/reservation/unit/controller/ReservationRestControllerTest.java
  src/test/java/com/fc/shimpyo_be/domain/reservation/unit/service/ReleaseRoomsServiceTest.java
  src/test/java/com/fc/shimpyo_be/domain/reservationproduct/docs/ReservationProductRestControllerDocsTest.java
  src/test/java/com/fc/shimpyo_be/domain/reservationproduct/unit/controller/ReservationProductRestControllerTest.java
  src/test/java/com/fc/shimpyo_be/domain/reservationproduct/unit/service/ReservationProductServiceTest.java
Labels: 🛠️feature, ✅Test

#61 feat: Rest docs adoc 파일 작성 (별점, 예약, 예약상품)
  src/docs/asciidoc/reservation/reservation-api.adoc
  src/docs/asciidoc/reservationproduct/reservation-product-api.adoc
  src/docs/asciidoc/star/star-api.adoc
  src/test/java/com/fc/shimpyo_be/domain/reservation/docs/ReservationRestControllerDocsTest.java
  src/test/java/com/fc/shimpyo_be/domain/reservationproduct/docs/ReservationProductRestControllerDocsTest.java
Labels: 📚document

#70 refactor: Security 리팩토링 및 로그 레벨 수정
  src/main/java/com/fc/shimpyo_be/global/config/jwt/JwtAccessDeniedHandler.java
  src/main/java/com/fc/shimpyo_be/global/config/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/com/fc/shimpyo_be/global/config/jwt/JwtSecurityConfig.java
  src/main/java/com/fc/shimpyo_be/global/config/jwt/JwtTokenProvider.java
Labels: 🚧refactoring

#71 feat: 글로벌 예외 처리 시 로깅 구현
  src/main/java/com/fc/shimpyo_be/global/exception/GlobalControllerAdvice.java
Labels: 🛠️feature

#72 Log : 상품, 장바구니 컨트롤러 logging 작업을 합니다.
  src/main/java/com/fc/shimpyo_be/domain/cart/controller/CartRestController.java
  src/main/java/com/fc/shimpyo_be/domain/product/controller/ProductRestController.java
Labels: 🛠️feature

#74 feat: 별점 평균 업데이트 기능 개발
  src/main/java/com/fc/shimpyo_be/domain/product/entity/Product.java
  src/main/java/com/fc/shimpyo_be/domain/reservation/dto/response/ReservationInfoResponseDto.java
  src/main/java/com/fc/shimpyo_be/domain/reservation/service/ReservationService.java
  src/main/java/com/fc/shimpyo_be/domain/reservationproduct/repository/ReservationProductRepository.java
  src/main/java/com/fc/shimpyo_be/domain/star/dto/request/StarRegisterRequestDto.java
  src/main/java/com/fc/shimpyo_be/domain/star/exception/CannotBeforeCheckOutException.java
  src/main/java/com/fc/shimpyo_be/domain/star/repository/StarRepository.java
  src/main/java/com/fc/shimpyo_be/domain/star/service/StarService.java
  src/main/java/com/fc/shimpyo_be/global/exception/ErrorCode.java
  src/test/java/com/fc/shimpyo_be/domain/reservation/docs/ReservationRestControllerDocsTest.java
  src/test/java/com/fc/shimpyo_be/domain/reservation/unit/controller/ReservationRestControllerTest.java
  src/test/java/com/fc/shimpyo_be/domain/star/docs/StarRestControllerDocsTest.java
  src/test/java/com/fc/shimpyo_be/domain/star/unit/controller/StarRestControllerTest.java
  src/test/java/com/fc/shimpyo_be/domain/star/unit/service/StarServiceTest.java
Labels: 🛠️feature, 🚧refactoring, ✅Test

#76 docs: README 작성
  README.md
  src/main/resources/image/architecture.png
  src/main/resources/image/cart-docs.png
  src/main/resources/image/cd.png
  src/main/resources/image/ci.png
  src/main/resources/image/erd.png
  src/main/resources/image/index-docs.png
  src/main/resources/image/member-docs.png
  src/main/resources/image/product-docs.png
  src/main/resources/image/reservation-docs.png
  src/main/resources/image/reservation-product-docs.png
  src/main/resources/image/star-docs.png
Labels: 📚document

#79 fix: 예약 API Rest Docs Test 수정
  src/test/java/com/fc/shimpyo_be/domain/reservation/docs/ReservationRestControllerDocsTest.java
Labels: 📚document, 🧑🏻‍🔧fix, ✅Test

#82 docs: 이미지 변경
  src/main/resources/image/reservation-docs.png
  src/main/resources/image/star-docs.png
Labels: 📚document

#83 docs: 리드미 팀원 부분 수정
  README.md
Labels: 📚document

#85 fix: yaml 파일 gitignore 추가
  .gitignore
Labels: 🧑🏻‍🔧fix

#86 fix: 모든 yaml 파일 gitignore 설정
  .gitignore
Labels: 🧑🏻‍🔧fix
